apiVersion: apps/v1
kind: Deployment
metadata:
  name: invoice-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: invoice
  template:
    metadata:
      labels:
        app: invoice
    spec:
      containers:
        - name: invoice
          image: yaserkt786/invoice:latest
          

---
apiVersion: v1
kind: Service
metadata: 
  name: invoice-srv
spec: 
  selector:
    app: invoice
  ports:
    - name: invoice
      protocol: TCP
      port: 4000
      targetPort: 4000
