apiVersion: apps/v1
kind: Deployment
metadata:
  name: organization-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: organization
  template:
    metadata:
      labels:
        app: organization
    spec:
      containers:
        - name: organization
          image: yaserkt786/organization:latest
          

---
apiVersion: v1
kind: Service
metadata: 
  name: organization-srv
spec: 
  selector:
    app: organization
  ports:
    - name: organization
      protocol: TCP
      port: 4000
      targetPort: 4000
