apiVersion: apps/v1
kind: Deployment
metadata:
  name: tenants-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tenants
  template:
    metadata:
      labels:
        app: tenants
    spec:
      containers:
        - name: tenants
          image: yaserkt786/tenants:latest
          

---
apiVersion: v1
kind: Service
metadata: 
  name: tenants-srv
spec: 
  selector:
    app: tenants
  ports:
    - name: tenants
      protocol: TCP
      port: 4000
      targetPort: 4000
